modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="mode"
version="1.0.0"
displayName="Mode Example Mod"
updateJSONURL=""
displayURL=""
logoFile=""
credits=""
authors=""
description='''
An example mod skeleton.
'''

[[dependencies.mode]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.mode]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
